### ISSUE TITLE
Process handling bug - get a closed handle from second process

### ISSUE THREAD

**Issue by asb** [xolox/lua-apr#1]
I can always launch the first process and manipulate stdin, stdout, stderr fine, but the second process to be launched gives me closed filehandles. For instance, the following example results in and error `attempt to use a closed file` on line 17.

```
apr = require('apr')

p = apr.proc_create 'ls'
p:cmdtype_set('shellcmd/env')
p:io_set('none', 'parent-block', 'none')
p:exec()
output = p:out_get()
print(output:read())
output:close()
p:wait(true)

p = apr.proc_create 'ls'
p:cmdtype_set('shellcmd/env')
p:io_set('none', 'parent-block', 'none')
p:exec()
output = p:out_get()
print(output:read())
output:close()
p:wait(true)
```

**Comment by xolox** [comment]
Thanks for the bug report Alex. I guess I've found the problem: `lua_newuserdata()` installs a default environment table which breaks the Lua/APR binding because I assumed there wasn't a default environment. I can't find this in the Lua 5.1 manual but [the lua-users wiki](http://lua-users.org/wiki/UserDataRefinement) confirms my suspicion.

I'm working on a bug fix, shouldn't take more than an hour or so.

**Comment by xolox** [comment]
I just pushed version `0.9.6` (14efa65b3ae37c2f10ba192db08e52fffe14363b) which fixes this problem so I'm closing this issue now. Thanks again for the feedback!
