### ISSUE TITLE
Build on Mac OS X

### ISSUE THREAD

**Issue by mkottman** [xolox/lua-apr#10]
In order to successfully build lua-apr on Mac OS X (Lion), I had to modify the file `etc/make.lua` to include paths for Lua in lflags, as these were missing:

```
diff --git a/etc/make.lua b/etc/make.lua
index 09d8bd1..7ed366f 100644
--- a/etc/make.lua
+++ b/etc/make.lua
@@ -154,6 +154,9 @@ end

 local function getlflags()
   local flags = {}
+  mergeflags(flags, 'pkg-config --libs lua5.1') -- Debian/Ubuntu
+  mergeflags(flags, 'pkg-config --libs lua-5.1') -- FreeBSD
+  mergeflags(flags, 'pkg-config --libs lua') -- Arch Linux
   -- Linker flags for APR 1.
   mergeflags(flags, 'apr-1-config --link-ld --libs')
   mergeflags(flags, 'pkg-config --libs apr-1')
```

Here is the result on running tests (looks ok, not sure about io_net):

```
Running base64 tests: OK
Running crypt tests: OK
Running date tests: OK
Running dbd tests: Skipped!
Running dbm tests: OK
Running env tests: OK
Running filepath tests: OK
Running fnmatch tests: OK
Running getopt tests: OK
Running http tests: OK
Running io_dir tests: Failed! (/usr/local/share/lua/5.1/apr/test/io_dir.lua:23: File exists)
Running io_file tests: OK (2.02s)
Running io_net tests:  *** Lua/APR status_to_name(670008) failed, might be a bug?
Failed! (/usr/local/share/lua/5.1/apr/test/io_net.lua:22: nodename nor servname provided, or not known)
Running ldap tests: 
Warning: Failed to bind to LDAP server, I'm assuming it's not available (reason: Can't contact LDAP server)
Skipped!
Running memcache tests: 
Warning: Looks like memcached isn't available! (Connection refused)
Skipped!
Running misc tests: OK
Running pollset tests: OK (1.02s)
Running proc tests: OK
Running shm tests: OK
Running signal tests: OK
Running str tests: OK
Running thread tests: OK (1.02s)
Running thread_queue tests: OK
Running time tests: OK
Running uri tests: OK
Running user tests: OK
Running uuid tests: OK
Running xlate tests: OK
Running xml tests: OK
Done!
```

**Comment by mkottman** [comment]
After some more reading [1] and testing, the patch I provided is actually wrong, because it should not be needed to link a module directly to Lua (at least on non-Windows), because it breaks the module in LuaJIT. The following actually works for both Lua and LuaJIT on my Mac OS X:

```
diff --git a/Makefile b/Makefile
index 5002adb..58e4c47 100644
--- a/Makefile
+++ b/Makefile
@@ -82,6 +82,12 @@ override CFLAGS += -fprofile-arcs -ftest-coverage
 override LFLAGS += -fprofile-arcs
 endif

+ifeq (Darwin,$(shell uname -s))
+LINK_TYPE = -bundle -undefined dynamic_lookup
+else
+LINK_TYPE = -shared
+endif
+
 # Names of compiled object files.
 OBJECTS = $(patsubst %.c,%.o,$(SOURCES))

@@ -91,7 +97,7 @@ default: $(BINARY_MODULE)

 # Build the binary module.
 $(BINARY_MODULE): $(OBJECTS) Makefile
-   $(CC) -shared -o $@ $(OBJECTS) $(LFLAGS) || lua etc/make.lua --check
+   $(CC) $(LINK_TYPE) -o $@ $(OBJECTS) $(LFLAGS) || lua etc/make.lua --check

 # Build the standalone libapreq2 binding.
 $(APREQ_BINARY): etc/apreq_standalone.c Makefile
```

[1] http://lua-users.org/wiki/BuildingModules

**Comment by xolox** [comment]
Hi Michal,

Thanks for the feedback and for suggesting a patch! I just included the change you suggested, I hope I didn't break it in the process (I don't have any Macs available so can't actually test it).

When I have some more time on my hands (hopefully later this week) I'll look through the test output you gave to see why the tests for the `dbd`, `io_dir` and `io_net` modules are not working as they should (I have some suspicions).

 - Peter

**Comment by mkottman** [comment]
I confirm that the module builds OK out-of-the-box right now. I am not sure if this issue should be closed or left open until the tests are resolved...

**Comment by xolox** [comment]
Hi Michal,

Can you run the tests once more with the latest code? I'm hoping that the `io_dir` and `io_net` problems in the test suite on Mac OS X are now resolved. I'm not sure what to make of the failing `dbd` tests though, I'm surprised the tests don't print a warning message or anything.

Thanks in advance!

 - Peter

**Comment by mkottman** [comment]
First comment: I had to add `math.randomseed(os.time())` to the io_dir test, because the test was creating the same directory and the call to `dir_create` failed with 'File exists!'.

I got other assertions which seem to be caused by encoding (`assert(nonascii[i] == entries[i])`):

```
...
Running io_dir tests: Failed! (/usr/local/share/lua/5.1/apr/test/io_dir.lua:75: assertion failed!)
Running io_file tests: OK (0.56s)
Running io_net tests:  *** Lua/APR status_to_name(670008) failed, might be a bug?
Warning: Assertion failed with nodename nor servname provided, or not known (This test can apparently fail on Mac OS X so I made it a soft assertion)OK
...
```

**Comment by xolox** [comment]
Thanks for testing and sorry for all the back and forth :-). The `io_dir` tests now seed the random number generator and the encoding problem should now give a much more descriptive error message. Can you try it again? I'm hoping the new error message will tell us what's wrong.

**Comment by mkottman** [comment]
Okay, this seems to be some kind of Unicode normalization. I changed the test and added the following:

```
if not pcall(function()
  for i = 1, math.max(#nonascii, #entries, #rewinded) do
    if nonascii[i] ~= entries[i] then
      print('mismatch 1', i)
      print(nonascii[i], nonascii[i]:byte(1,#nonascii[i]))
      print(entries[i], entries[i]:byte(1,#entries[i]))
    end
```

And this is what I get:

```
Running io_dir tests: mismatch 1 1
Cassius - Au Rêve 67 97 115 115 105 117 115 32 45 32 65 117 32 82 195 170 118 101
Cassius - Au Rêve 67 97 115 115 105 117 115 32 45 32 65 117 32 82 101 204 130 118 101
```

**Comment by xolox** [comment]
Hi Michal,

Thanks for trying again, and helping to debug the issue. I didn't think about Unicode normalization, smart of you to dump the raw bytes, I should have done that the first time around. I'm guessing I could cheat by changing the test to start with the normalized Unicode form, but somehow that does not feel right. Anyway I'm completely new to the concept of Unicode normalization at the file system level, which pretty much seems to suck...

I compared both forms (my original _Cassius - Au Rêve_ and the normalized  _Cassius - Au Rêve_) and looked up [the album title on Wikipedia](http://en.wikipedia.org/wiki/Au_R%C3%AAve) to verify which is the proper form and it turns out that the original is the proper form. I can even see in my web browser (Mozilla Firefox 3.6 on Ubuntu Linux) that the original form looks good and the normalized form looks wrong; the circumflex is rendered to the right of the e.

I guess Unicode normalization is a fact of life on Mac OS X so I should just change the tests to use the normalized forms, but since that's wrong (as I explained above) I will instead make the tests aware of Unicode normalization explicitly :-) (however since I don't have a function to give me the normalized forms of Unicode strings I will have to include the normalized forms explicitly).

 - Peter

**Comment by xolox** [comment]
Since I don't have a Mac available I took the normalized output you sent me and used Python's `unicodedata.normalize()` function to find out which normalization form was being applied, then applied that form of normalization to each Unicode string used in the io_dir tests.

I'm not sure if Unicode normalization is always enabled on Macs, in that case every Mac user running the test suite will from now on get a warning when the test suite detects Unicode normalization being applied (because I think it's wrong, if you're curious see my last commit message).

I hope that the io_dir test now works out of the box on Mac OS X! Thanks for your feedback all of the testing :-)

 - Peter

**Comment by mkottman** [comment]
They do not (yet) - you seem to have missed that you removed the `nonascii` variable, but did not change the code to reference `nonascii_canonical`. I had to do this to make the tests work (the simplest change I though of):

```
diff --git a/test/io_dir.lua b/test/io_dir.lua
index 2e03c55..6bb3f4c 100644
--- a/test/io_dir.lua
+++ b/test/io_dir.lua
@@ -49,7 +49,7 @@ local msi = 'Mindless Self Indulgence - Despierta Los Niños'
 local manu_chao = 'Manu Chao - Próxima Estación; Esperanza'
 local cassius = 'Cassius - Au Rêve'
 local yoko_kanno = '菅野 よう子'
-local nonascii_canonical = { msi, manu_chao, cassius, yoko_kanno }
+local nonascii = { msi, manu_chao, cassius, yoko_kanno }

 -- Mac OS X applies Unicode normalization on the file system level. This means
 -- you can write a file without getting any errors, but when you check for the
```

**Comment by xolox** [comment]
Crap, sorry about that, I had some unrelated changes in my working directory which broke the build and tests so I skipped them. Note to self: Never skip the tests! I will learn to use `git stash` more often :-).

**Comment by mkottman** [comment]
Okay, now the tests go all the way :)
