### ISSUE TITLE
Wish support UDP socket, now UDP not work.

### ISSUE THREAD

**Issue by zhaozg** [xolox/lua-apr#9]
udp socket in apr used as client can work, but when use as server, will crash and not receive any data.

**Comment by xolox** [comment]
I've never worked with UDP server sockets before so it took me a while to realize how it works. Apparently one cannot call `accept()` on an UDP socket because UDP is stateless. Instead one should call `recvfrom()` to listen for UDP messages. For an example see the test code I came up with (quoted below). I haven't implemented `sendto()` yet, but as the test code shows that may not even be necessary (I guess it is an optimization).

``` lua
local udp_port = math.random(10000, 50000)
local udp_socket = assert(apr.socket_create 'udp')
assert(udp_socket:bind('*', udp_port))

local server = apr.thread(function(udp_socket)
  local client, data = assert(udp_socket:recvfrom())
  assert(client.address == '127.0.0.1')
  assert(client.port >= 1024)
  assert(data == 'booyah!')
end, udp_socket)

local client = apr.thread(function(udp_port)
  local status, apr = pcall(require, 'apr')
  if not status then
    pcall(require, 'luarocks.require')
    apr = require 'apr'
  end
  local socket = assert(apr.socket_create 'udp')
  assert(socket:connect('127.0.0.1', udp_port))
  assert(socket:write 'booyah!')
  assert(socket:close())
end, udp_port)

assert(server:join())
assert(client:join())
```

I hope this is what you had in mind?

**Comment by zhaozg** [comment]
it work
